apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  labels:
    app: frontend-ui
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
        component: frontend
    spec:
      containers:
      - name: frontend-ui
        image: sliitprojectmail/event-sync-frontend-ui:c9f3762273421c4f93c7909a992afc986c9a9b16
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_GATEWAY_URL
          value: "/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
