apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
  labels:
    app: registration-service
    component: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
        component: microservice
    spec:
      containers:
      - name: registration-service
        image: sliitprojectmail/event-sync-registration-service:f8a3ba8f66c59b2f892b42de68084bbeb8cdd95a
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: event-sync-secrets
              key: MONGO_URI_REGISTRATION
        - name: USER_SERVICE_URL
          value: "http://user-service:3001"
        - name: EVENT_SERVICE_URL
          value: "http://event-service:3002"
        - name: KAFKA_BROKER
          value: "kafka-svc:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 20
          periodSeconds: 30
